export interface RoastLine { text: string }

/** Replace {key} tokens with values from the context map. */
export function interpolate(text: string, ctx: Record<string, string | number>): string {
  return text.replace(/\{(\w+)\}/g, (_, k) => String(ctx[k] ?? `{${k}}`))
}

export const TIER_ROASTS: Record<number, RoastLine[]> = {
  0: [
    { text: "Oh good, you found the game. That's step one." },
    { text: "I'd wish you luck but I don't want to lie to your face this early." },
    { text: "Promising start. I mean, the game loaded. That part was promising." },
    { text: "The bricks are unaware of what's coming. Honestly, same." },
    { text: "Welcome. I'm already bracing myself." },
    { text: "The paddle is responding to your input. Exceeding expectations so far." },
    { text: "Don't worry, I grade on a curve. A very generous curve." },
    { text: "I've seen worse. Not recently, but historically." },
    { text: "You've located the ball. That's more than some manage." },
    { text: "Let's keep expectations appropriately managed." },
  ],
  1: [
    { text: "The ball was RIGHT there. Like, right there. I'm concerned about your depth perception." },
    { text: "My grandma could've hit that and she's a JSON file." },
    { text: "You move the paddle with your mouse, not your thoughts. I checked." },
    { text: "That was... a choice. A wrong one, but still a choice." },
    { text: "I've seen better reflexes from a loading spinner." },
    { text: "The ball is not going to aim itself. Unfortunately." },
    { text: "You had a one-in-one chance to hit that. Math is having a rough day." },
    { text: "Was that intentional? I genuinely cannot tell." },
    { text: "Interesting strategy. By 'interesting' I mean 'incorrect.'" },
    { text: "The bricks are starting to feel comfortable. That's not good." },
    { text: "I've seen more precise movements from a trackpad on a bumpy bus." },
    { text: "The ball went exactly where you weren't. Impressive consistency." },
  ],
  2: [
    { text: "Are you playing this with your feet? Genuine question." },
    { text: "I've seen better hand-eye coordination from a 404 error." },
    { text: "I'm going to file a missing persons report for your skill." },
    { text: "This is what happens when tutorials go unread." },
    { text: "I've recalibrated my expectations. Downward. Significantly." },
    { text: "At some point, the game has to wonder what it did wrong." },
    { text: "Your paddle moved. Unfortunately not toward the ball." },
    { text: "I'm not rooting against you. I'm just keeping realistic notes." },
    { text: "The ball has now traveled more distance than your skill level warrants." },
    { text: "We're at the stage where I have concerns I didn't have before." },
    { text: "I've stopped being surprised and started taking detailed notes." },
    { text: "The bricks filed a complaint. I'm reviewing it favorably." },
  ],
  3: [
    { text: "If failure was a speedrun category, you'd still somehow be slow." },
    { text: "The ball has more purpose in life than this gameplay suggests." },
    { text: "You're not losing. Losing implies there was a competition." },
    { text: "I just checked — there IS a refund for the time I've spent watching you." },
    { text: "The bricks have started chatting amongst themselves. They feel safe." },
    { text: "Your paddle is doing its best. Your paddle deserves better." },
    { text: "I've seen more coordinated activity from a merge conflict." },
    { text: "The ball is trying. It really is. You're not helping it." },
    { text: "At this point, the arena is more of a witness than a venue." },
    { text: "I'm documenting this for science. Specifically, the science of failure." },
    { text: "The laws of physics are begging for you to work with them, not against them." },
    { text: "Something has gone structurally wrong here. I don't know what. Possibly everything." },
  ],
  4: [
    { text: "I've started a support group for the pixels you've wasted." },
    { text: "Your paddle called. It wants to see other players." },
    { text: "I'm not mad. I'm just deeply, profoundly disappointed. Actually also mad." },
    { text: "I've seen better aim from a random number generator. I tested it. It won." },
    { text: "If your gameplay was a resume, the position would be eliminated." },
    { text: "The bricks have unionized. They're demanding a competent opponent." },
    { text: "This isn't a game anymore. This is performance art about failure." },
    { text: "I need you to understand that I've seen things. This is among the worst." },
    { text: "The arena has submitted a formal complaint. I'm reading it. It's quite long." },
    { text: "At some point the ball just gave up. I respect that decision." },
    { text: "There are people who have never played a game in their life who are doing better than this right now." },
    { text: "I've sent a wellness check to your hand-eye coordination. It's not responding." },
  ],
  5: [
    { text: "Wait... was that on purpose? No way that was on purpose." },
    { text: "Okay that was almost impressive. Almost." },
    { text: "Don't let this streak go to your head. Your head clearly can't handle much." },
    { text: "I'd clap but I don't want to give you false confidence." },
    { text: "Something is working. I'm not sure what. Don't change it." },
    { text: "I'm cautiously pessimistic about your current momentum." },
    { text: "That combo was... competent. I didn't think I'd have to say that." },
    { text: "You're doing well, which means you're about to do something catastrophic." },
    { text: "Progress detected. My expectations were wrong. They have been updated." },
    { text: "If this keeps up I may have to switch to mild disappointment mode." },
  ],
}

export const EVENT_ROASTS: Record<string, RoastLine[]> = {
  ball_lost: [
    { text: "And there it goes. Into the void. Like your dignity." },
    { text: "Ball lost. Along with the thread of what you were even trying to do." },
    { text: "{lives} lives remaining. Plan accordingly. Or don't. You won't." },
    { text: "The ball has retired from your care. Can't say I blame it." },
    { text: "Lost. Again. The ball is filing for separation." },
    { text: "I warned you. I did. You didn't listen. Nobody listens." },
  ],
  afk: [
    { text: "Hello? Is anyone operating this paddle?" },
    { text: "I've detected what scientists call 'complete inaction.'" },
    { text: "The ball is still in play. You are not." },
    { text: "Taking a break? The bricks are using this time to train." },
    { text: "I've seen faster reaction times from a parked car." },
  ],
  level_start: [
    { text: "New level. Fresh opportunity to disappoint me." },
    { text: "Bricks restored. Your competence, presumably, has not been." },
    { text: "Level {level}. Let's see if this is the one where things click." },
    { text: "The bricks have been briefed. They are not worried." },
    { text: "Another chance. Let's be honest about our expectations." },
  ],
  level_clear: [
    { text: "You cleared it. I'm choosing to believe that was intentional." },
    { text: "Level cleared. I'll revise my threat assessment from 'none' to 'minimal.'" },
    { text: "Against all projections, you did it. Don't get comfortable." },
    { text: "Fine. You win this round. There are more rounds." },
    { text: "Cleared. The bricks were too shocked to object." },
  ],
  game_over: [
    { text: "Game over. The bricks have won and they deserve it." },
    { text: "That's all. Review what happened here. Learn from it. Please." },
    { text: "Final score: {score}. I've seen more impressive numbers on a tax form." },
    { text: "The game is over. You have questions. The answers are uncomfortable." },
    { text: "You gave it everything. Everything was not enough." },
  ],
  pause: [
    { text: "Paused. Taking stock? Taking a snack? Probably the snack." },
    { text: "Game paused while you consider your options. Consider them harder." },
    { text: "ESC pressed. The universal symbol of 'I need a moment.'" },
    { text: "Paused. Reflecting on choices. Good. There's a lot to reflect on." },
    { text: "You've paused again. The game is starting to take it personally." },
  ],
  first_brick: [
    { text: "A brick. You hit a brick. The bare minimum has been achieved." },
    { text: "Solid contact. I'd say 'impressive' but we both know that's not right." },
    { text: "One down. The false confidence phase has begun." },
    { text: "First brick falls. Brief and unearned triumph acknowledged." },
    { text: "One brick. Good. Don't stop there. You usually stop there." },
  ],
  combo: [
    { text: "×{combo}. I'm going to need to verify this data." },
    { text: "A {combo}-hit combo. I'll update my risk assessment." },
    { text: "You're hot right now. That usually precedes a catastrophic miss." },
    { text: "×{combo}. Noted. Updated. Still skeptical." },
    { text: "That combo is {combo} hits. My respect is building. Against my will." },
  ],
  explosive: [
    { text: "Oh. OH. That's a lot of bricks gone at once. I didn't expect that either." },
    { text: "Chain reaction. Nice. I'm grudgingly acknowledging this." },
    { text: "The explosion was more impressive than your usual gameplay. I've noted this anomaly." },
    { text: "Boom. Multiple bricks. I'm recalculating everything." },
  ],
  troll: [
    { text: "You're welcome. Those bricks needed that." },
    { text: "You hit the troll brick. That was my doing. I'm very proud of myself." },
    { text: "{healed} bricks restored. I'd say sorry but I'm not." },
    { text: "The troll brick has spoken. Progress has been reversed. I'm delighted." },
    { text: "I helped. You're welcome. Please don't thank me." },
  ],
  flailing: [
    { text: "The paddle is statistically thrashing. Please calm down." },
    { text: "That's some erratic movement. Science would call this flailing." },
    { text: "I've seen calmer error logs than your erratic paddle movement." },
    { text: "The paddle is thrashing around. The ball finds this embarrassing." },
    { text: "Stabilize. Please. For everyone's sake." },
  ],
  camping: [
    { text: "The paddle is parked. The ball disagrees with this choice." },
    { text: "You've found a corner and you're staying there. Brave. Wrong, but brave." },
    { text: "I see the paddle has chosen one side of the arena to live in now." },
    { text: "Camping detected. The ball filed a complaint." },
    { text: "The paddle planted itself. The ball remains unimpressed." },
  ],
  boss_taunt: [
    { text: "Is that all you got? I've been hit harder by lag spikes." },
    { text: "I'm not even trying yet. This is my warm-up phase." },
    { text: "You call that an attack? Adorable." },
    { text: "I've survived harder debugging sessions than this." },
    { text: "Hit me again. I'll wait. Seriously, I have time." },
  ],
}
